<?php

declare (strict_types=1);
namespace Illuminate\Database;

use Exception;
use Illuminate\Database\Query\Grammars\My_Sql_Grammar as QueryGrammar;
use Illuminate\Database\Query\Processors\My_Sql_Processor;
use Illuminate\Database\Schema\Grammars\My_Sql_Grammar as SchemaGrammar;
use Illuminate\Database\Schema\My_Sql_Builder;
use Illuminate\Database\Schema\My_Sql_Schema_State;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Str;
use PDO;
class My_Sql_Connection extends Connection
{
    /**
     * The last inserted ID generated by the server.
     *
     * @var string|int|null
     */
    protected $last_insert_id;
    /**
     * {@inheritdoc}
     */
    public function get_driver_title(): string
    {
        return $this->is_maria() ? 'MariaDB' : 'MySQL';
    }
    /**
     * Run an insert statement against the database.
     *
     * @param  string  $query
     * @param  array  $bindings
     * @param  string|null  $sequence
     * @return bool
     */
    public function insert($query, $bindings = [], $sequence = null)
    {
        return $this->run($query, $bindings, function ($query, array $bindings) use ($sequence) {
            if ($this->pretending()) {
                return true;
            }
            $statement = $this->get_pdo()->prepare($query);
            $this->bind_values($statement, $this->prepare_bindings($bindings));
            $this->records_have_been_modified();
            $result = $statement->execute();
            $this->last_insert_id = $this->get_pdo()->last_insert_id($sequence);
            return $result;
        });
    }
    /**
     * Escape a binary value for safe SQL embedding.
     *
     * @param  string  $value
     */
    protected function escape_binary($value): string
    {
        $hex = bin2hex($value);
        return "x'{$hex}'";
    }
    /**
     * Determine if the given database exception was caused by a unique constraint violation.
     */
    protected function is_unique_constraint_error(Exception $exception): bool
    {
        return (bool) preg_match('#Integrity constraint violation: 1062#i', $exception->get_message());
    }
    /**
     * Get the connection's last insert ID.
     *
     * @return string|int|null
     */
    public function get_last_insert_id()
    {
        return $this->last_insert_id;
    }
    /**
     * Determine if the connected database is a MariaDB database.
     */
    public function is_maria(): bool
    {
        return str_contains((string) $this->get_pdo()->get_attribute(PDO::ATTR_SERVER_VERSION), 'MariaDB');
    }
    /**
     * Get the server version for the connection.
     */
    public function get_server_version(): string
    {
        return str_contains($version = parent::get_server_version(), 'MariaDB') ? Str::between($version, '5.5.5-', '-MariaDB') : $version;
    }
    /**
     * Get the default query grammar instance.
     */
    protected function get_default_query_grammar(): \Illuminate\Database\Query\Grammars\My_Sql_Grammar
    {
        return new Query_Grammar($this);
    }
    /**
     * Get a schema builder instance for the connection.
     */
    public function get_schema_builder(): \Illuminate\Database\Schema\My_Sql_Builder
    {
        if (is_null($this->schema_grammar)) {
            $this->use_default_schema_grammar();
        }
        return new My_Sql_Builder($this);
    }
    /**
     * Get the default schema grammar instance.
     */
    protected function get_default_schema_grammar(): \Illuminate\Database\Schema\Grammars\My_Sql_Grammar
    {
        return new Schema_Grammar($this);
    }
    /**
     * Get the schema state for the connection.
     */
    public function get_schema_state(?Filesystem $files = null, ?callable $process_factory = null): \Illuminate\Database\Schema\My_Sql_Schema_State
    {
        return new My_Sql_Schema_State($this, $files, $process_factory);
    }
    /**
     * Get the default post processor instance.
     */
    protected function get_default_post_processor(): \Illuminate\Database\Query\Processors\My_Sql_Processor
    {
        return new My_Sql_Processor();
    }
}